#!/bin/bash

# Quick diagnostic for stuck upload at 27%

echo "🔍 Upload Stuck at 27% - Quick Diagnostics"
echo "=========================================="
echo ""
echo "27% means the actual file upload is ~10% complete"
echo "This suggests XHR started but stopped reporting progress"
echo ""
echo "📋 What to check in Browser Console (F12):"
echo ""
echo "1. Look for the last log message. Should be one of:"
echo "   [UploadService] Starting XHR upload to presigned URL"
echo "   [UploadService] Sending file via XHR PUT..."
echo "   [Upload] Progress: { percent: ... }"
echo ""
echo "2. Check Network tab (F12 → Network):"
echo "   - Look for PUT request to storage"
echo "   - Is it still 'pending'?"
echo "   - Or did it fail with an error?"
echo ""
echo "3. Common causes at 27%:"
echo "   a) Large file + slow connection = looks stuck but still uploading"
echo "   b) Network interruption = stalled transfer"
echo "   c) CORS error = request blocked"
echo "   d) Presigned URL expired = 403 error"
echo ""
echo "🔧 Quick Fixes to Try:"
echo ""
echo "1. Check if it's actually uploading (just slow):"
echo "   - Look at Network tab"
echo "   - Check if bytes are increasing"
echo "   - Large files can take minutes"
echo ""
echo "2. Try a smaller file first:"
echo "   - Use file < 10MB to test"
echo "   - Should complete in 10-20 seconds"
echo ""
echo "3. Check console for errors:"
echo "   - Red error messages?"
echo "   - CORS errors?"
echo "   - 403/500 responses?"
echo ""
echo "4. Restart upload:"
echo "   - Refresh page (F5)"
echo "   - Try again"
echo ""
echo "📊 In Console, run this to check upload status:"
echo ""
echo "// Paste in browser console:"
echo "performance.getEntriesByType('resource')"
echo "  .filter(r => r.name.includes('storage'))"
echo "  .forEach(r => console.log(r.name, r.transferSize, r.duration))"
echo ""
echo "This shows storage requests and their progress"
echo ""
