-- ============================================================
-- FIX VIDEO PERSISTENCE & PUBLIC VISIBILITY FOR ALL USERS
-- Run this in Supabase SQL Editor to ensure:
-- 1. Videos persist after page refresh
-- 2. All users can see all uploaded videos (TikTok-style)
-- 3. ALL users follow the same pattern as kenxokent account
-- ============================================================
-- IMPORTANT: This uses the "posts" table (same as kenxokent account)
-- ============================================================

-- STEP 1: Ensure posts table exists with correct structure (kenxokent's working system)
CREATE TABLE IF NOT EXISTS posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  video_path TEXT NOT NULL,
  description TEXT DEFAULT '',
  category TEXT DEFAULT 'comedy',
  visibility TEXT DEFAULT 'public' CHECK (visibility IN ('public', 'private', 'friends')),
  likes_count INTEGER DEFAULT 0,
  comments_count INTEGER DEFAULT 0,
  shares_count INTEGER DEFAULT 0,
  views_count INTEGER DEFAULT 0,
  poster_url TEXT,
  duration INTEGER DEFAULT 0,
  location TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- STEP 2: Add missing columns to existing posts table (if they don't exist)
DO $$ 
BEGIN
  -- Add visibility column if missing
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='posts' AND column_name='visibility') THEN
    ALTER TABLE posts ADD COLUMN visibility TEXT DEFAULT 'public' CHECK (visibility IN ('public', 'private', 'friends'));
  END IF;
  
  -- Add category column if missing
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='posts' AND column_name='category') THEN
    ALTER TABLE posts ADD COLUMN category TEXT DEFAULT 'comedy';
  END IF;
  
  -- Add poster_url column if missing
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='posts' AND column_name='poster_url') THEN
    ALTER TABLE posts ADD COLUMN poster_url TEXT;
  END IF;
  
  -- Add duration column if missing
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='posts' AND column_name='duration') THEN
    ALTER TABLE posts ADD COLUMN duration INTEGER DEFAULT 0;
  END IF;
  
  -- Add location column if missing
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='posts' AND column_name='location') THEN
    ALTER TABLE posts ADD COLUMN location TEXT;
  END IF;
  
  -- Add updated_at column if missing
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='posts' AND column_name='updated_at') THEN
    ALTER TABLE posts ADD COLUMN updated_at TIMESTAMPTZ DEFAULT NOW();
  END IF;
END $$;

-- STEP 3: Add indexes for performance (critical for 5M+ users)
CREATE INDEX IF NOT EXISTS idx_posts_user_id ON posts(user_id);
CREATE INDEX IF NOT EXISTS idx_posts_created_at ON posts(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_posts_visibility ON posts(visibility);
CREATE INDEX IF NOT EXISTS idx_posts_category ON posts(category);
CREATE INDEX IF NOT EXISTS idx_posts_public_created ON posts(visibility, created_at DESC) WHERE visibility = 'public';

-- STEP 4: Enable Row Level Security
ALTER TABLE posts ENABLE ROW LEVEL SECURITY;

-- STEP 5: Drop ALL old policies (clean slate)
DO $$ 
DECLARE
    policy_rec RECORD;
BEGIN
    FOR policy_rec IN 
        SELECT policyname 
        FROM pg_policies 
        WHERE tablename = 'posts'
    LOOP
        EXECUTE format('DROP POLICY IF EXISTS %I ON posts', policy_rec.policyname);
    END LOOP;
END $$;

-- STEP 6: Create NEW policies for TikTok-style public feed (exactly like kenxokent account)

-- ✅ CRITICAL: Everyone can VIEW all public posts (including anonymous users)
-- This is what makes videos appear in the feed for ALL users
CREATE POLICY "everyone_can_view_public_posts"
ON posts
FOR SELECT
TO public
USING (visibility = 'public');

-- ✅ Authenticated users can INSERT their own posts
CREATE POLICY "authenticated_users_can_create_posts"
ON posts
FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

-- ✅ Users can UPDATE their own posts
CREATE POLICY "users_can_update_own_posts"
ON posts
FOR UPDATE
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- ✅ Users can DELETE their own posts
CREATE POLICY "users_can_delete_own_posts"
ON posts
FOR DELETE
TO authenticated
USING (auth.uid() = user_id);

-- STEP 7: Grant table permissions
GRANT SELECT ON posts TO anon;
GRANT SELECT ON posts TO authenticated;
GRANT INSERT, UPDATE, DELETE ON posts TO authenticated;

-- Grant sequence permissions (find the actual sequence name dynamically)
DO $$ 
DECLARE
    seq_name TEXT;
BEGIN
    -- Find the sequence associated with posts.id column
    SELECT pg_get_serial_sequence('posts', 'id') INTO seq_name;
    IF seq_name IS NOT NULL THEN
        EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO authenticated', seq_name);
    END IF;
END $$;

-- STEP 8: Ensure storage bucket exists and has correct policies
-- Note: Bucket must be created first in Supabase Dashboard > Storage

-- Drop old storage policies
DO $$ 
DECLARE
    policy_rec RECORD;
BEGIN
    FOR policy_rec IN 
        SELECT policyname 
        FROM pg_policies 
        WHERE tablename = 'objects' 
        AND schemaname = 'storage'
        AND policyname LIKE '%video%'
    LOOP
        EXECUTE format('DROP POLICY IF EXISTS %I ON storage.objects', policy_rec.policyname);
    END LOOP;
END $$;

-- ✅ Everyone can VIEW video files (public read access)
CREATE POLICY "public_can_view_all_videos"
ON storage.objects
FOR SELECT
TO public
USING (bucket_id = 'videos');

-- ✅ Authenticated users can UPLOAD video files
CREATE POLICY "authenticated_can_upload_videos"
ON storage.objects
FOR INSERT
TO authenticated
WITH CHECK (bucket_id = 'videos' AND auth.role() = 'authenticated');

-- ✅ Users can UPDATE their own video files (for metadata)
CREATE POLICY "users_can_update_own_video_files"
ON storage.objects
FOR UPDATE
TO authenticated
USING (
  bucket_id = 'videos' AND
  (storage.foldername(name))[1] = auth.uid()::text
)
WITH CHECK (
  bucket_id = 'videos' AND
  (storage.foldername(name))[1] = auth.uid()::text
);

-- ✅ Users can DELETE their own video files
CREATE POLICY "users_can_delete_own_video_files"
ON storage.objects
FOR DELETE
TO authenticated
USING (
  bucket_id = 'videos' AND
  (storage.foldername(name))[1] = auth.uid()::text
);

-- STEP 9: Create profiles table if it doesn't exist
CREATE TABLE IF NOT EXISTS profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  username TEXT UNIQUE,
  full_name TEXT NOT NULL,
  avatar_url TEXT,
  bio TEXT,
  followers_count INTEGER DEFAULT 0,
  following_count INTEGER DEFAULT 0,
  likes_count INTEGER DEFAULT 0,
  coins INTEGER DEFAULT 0,
  is_seller BOOLEAN DEFAULT false,
  email TEXT,
  profile_views_enabled BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add profiles indexes
CREATE INDEX IF NOT EXISTS idx_profiles_username ON profiles(username);
CREATE INDEX IF NOT EXISTS idx_profiles_created_at ON profiles(created_at DESC);

-- Enable RLS on profiles
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

-- Profiles policies
DROP POLICY IF EXISTS "public_can_view_profiles" ON profiles;
DROP POLICY IF EXISTS "users_can_update_own_profile" ON profiles;
DROP POLICY IF EXISTS "users_can_insert_own_profile" ON profiles;

CREATE POLICY "public_can_view_profiles"
ON profiles FOR SELECT
TO public
USING (true);

CREATE POLICY "users_can_update_own_profile"
ON profiles FOR UPDATE
TO authenticated
USING (auth.uid() = id)
WITH CHECK (auth.uid() = id);

CREATE POLICY "users_can_insert_own_profile"
ON profiles FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = id);

GRANT SELECT ON profiles TO anon;
GRANT SELECT ON profiles TO authenticated;
GRANT INSERT, UPDATE ON profiles TO authenticated;

-- STEP 10: Create function to auto-update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger for posts
DROP TRIGGER IF EXISTS update_posts_updated_at ON posts;
CREATE TRIGGER update_posts_updated_at
  BEFORE UPDATE ON posts
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Create trigger for profiles
DROP TRIGGER IF EXISTS update_profiles_updated_at ON profiles;
CREATE TRIGGER update_profiles_updated_at
  BEFORE UPDATE ON profiles
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- STEP 11: Create view for posts with user info (for easier queries)
CREATE OR REPLACE VIEW posts_with_profiles AS
SELECT 
  p.*,
  pr.username,
  pr.full_name,
  pr.avatar_url,
  pr.followers_count
FROM posts p
LEFT JOIN profiles pr ON p.user_id = pr.id
WHERE p.visibility = 'public'
ORDER BY p.created_at DESC;

-- Grant access to view
GRANT SELECT ON posts_with_profiles TO anon;
GRANT SELECT ON posts_with_profiles TO authenticated;

-- STEP 12: Verify setup
SELECT 
  'Posts Table' as check_type,
  COUNT(*) as count
FROM posts
UNION ALL
SELECT 
  'Profiles Table' as check_type,
  COUNT(*) as count
FROM profiles
UNION ALL
SELECT 
  'Posts Policies' as check_type,
  COUNT(*) as count
FROM pg_policies 
WHERE tablename = 'posts'
UNION ALL
SELECT 
  'Storage Policies' as check_type,
  COUNT(*) as count
FROM pg_policies 
WHERE tablename = 'objects' AND schemaname = 'storage' AND policyname LIKE '%video%';

-- STEP 13: Test query (should return all posts)
-- Run this to verify posts are accessible:
-- SELECT id, user_id, description, created_at FROM posts WHERE visibility = 'public' ORDER BY created_at DESC LIMIT 10;

-- ============================================================
-- ✅ SETUP COMPLETE!
-- 
-- What this fixes:
-- 1. Videos now persist in database after page refresh
-- 2. All users (including anonymous) can see all uploaded videos
-- 3. Videos appear in public feed like TikTok
-- 4. Proper permissions for upload, update, delete
-- 5. Optimized indexes for 5M+ users
--
-- Next steps:
-- 1. Verify your Supabase environment variables in Vercel:
--    - VITE_SUPABASE_URL
--    - VITE_SUPABASE_ANON_KEY
--    - SUPABASE_SERVICE_ROLE_KEY (for API endpoints)
--
-- 2. Test by uploading a video and refreshing the page
--
-- 3. Check that videos appear for other users
-- ============================================================
