-- ===================================================================
-- PRESIGNED URL VIDEO UPLOAD SYSTEM
-- Complete database setup for video uploads with presigned URLs
-- ===================================================================

-- Step 1: Create posts table
CREATE TABLE IF NOT EXISTS posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  video_path TEXT NOT NULL,
  description TEXT DEFAULT '',
  category TEXT DEFAULT 'comedy',
  visibility TEXT DEFAULT 'public' CHECK (visibility IN ('public', 'private', 'friends')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Add indexes for performance
CREATE INDEX IF NOT EXISTS idx_posts_user_id ON posts(user_id);
CREATE INDEX IF NOT EXISTS idx_posts_created_at ON posts(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_posts_visibility ON posts(visibility);

-- Step 2: Enable Row Level Security
ALTER TABLE posts ENABLE ROW LEVEL SECURITY;

-- Step 3: RLS Policies for posts table
-- Allow all authenticated users to read public posts
CREATE POLICY "public_read_posts"
ON posts
FOR SELECT
USING (visibility = 'public' OR auth.uid() = user_id);

-- Allow users to insert their own posts
CREATE POLICY "users_insert_own_posts"
ON posts
FOR INSERT
WITH CHECK (auth.uid() = user_id);

-- Allow users to update their own posts
CREATE POLICY "users_update_own_posts"
ON posts
FOR UPDATE
USING (auth.uid() = user_id);

-- Allow users to delete their own posts
CREATE POLICY "users_delete_own_posts"
ON posts
FOR DELETE
USING (auth.uid() = user_id);

-- Step 4: Storage policies for videos bucket
-- Note: Run this in Supabase Dashboard if the bucket doesn't exist
-- Storage → Create new bucket → name: "videos" → Private

-- Allow public reads on videos (so anyone can watch)
CREATE POLICY IF NOT EXISTS "public_read_videos"
ON storage.objects
FOR SELECT
USING (bucket_id = 'videos');

-- Allow authenticated users to upload via signed URLs
CREATE POLICY IF NOT EXISTS "authenticated_upload_videos"
ON storage.objects
FOR INSERT
WITH CHECK (
  bucket_id = 'videos' 
  AND auth.role() = 'authenticated'
);

-- Allow users to delete their own videos
CREATE POLICY IF NOT EXISTS "users_delete_own_videos"
ON storage.objects
FOR DELETE
USING (
  bucket_id = 'videos' 
  AND auth.uid()::text = (storage.foldername(name))[1]
);

-- Step 5: Create a function to auto-update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = timezone('utc'::text, now());
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger for posts table
DROP TRIGGER IF EXISTS update_posts_updated_at ON posts;
CREATE TRIGGER update_posts_updated_at
  BEFORE UPDATE ON posts
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Step 6: Create a view for posts with user information
CREATE OR REPLACE VIEW posts_with_users AS
SELECT 
  p.*,
  u.id as author_id,
  u.email as author_email,
  u.raw_user_meta_data->>'username' as author_username,
  u.raw_user_meta_data->>'avatar_url' as author_avatar
FROM posts p
LEFT JOIN auth.users u ON p.user_id = u.id;

-- Step 7: Enable realtime for posts table (for live feed updates)
ALTER PUBLICATION supabase_realtime ADD TABLE posts;

-- ===================================================================
-- VERIFICATION QUERIES
-- ===================================================================

-- Check if posts table exists
SELECT EXISTS (
  SELECT FROM information_schema.tables 
  WHERE table_schema = 'public' 
  AND table_name = 'posts'
) AS posts_table_exists;

-- Check RLS policies
SELECT schemaname, tablename, policyname, permissive, roles, cmd, qual
FROM pg_policies
WHERE tablename = 'posts';

-- Check storage policies
SELECT *
FROM storage.policies
WHERE bucket_id = 'videos';

COMMENT ON TABLE posts IS 'Stores video posts uploaded via presigned URLs';
COMMENT ON COLUMN posts.video_path IS 'Relative path to video in Supabase storage (e.g., videos/123456-filename.mp4)';
COMMENT ON COLUMN posts.visibility IS 'Controls who can see the post: public, private, or friends';
